trigger:
  - master

pr:
  - master

stages:
#   - stage: restore
#     jobs:
#       - job: restore_api
#         steps:
#           - script: dotnet restore tour-api/aspnet

#       - job: restore_angular
#         steps:
#           - script: npm install --prefix tour-client/tour-heroes

  - stage: build
    jobs:
      - job: build_api
        steps:
          - script: dotnet build tour-api/aspnet/Tour.WebApi/*csproj

      - job: build_angular
        steps:
          - script: npm install --prefix tour-client/tour-heroes
          - script: npm run build --progress=false --prefix tour-client/tour-heroes
  
  # - stage: test
  #   jobs: 
  #     - job: test_api
  #       steps:
  #         - script: dotnet test tour-api/aspnet/Tour.Testing
        
  #     - job: test_angular
  #       steps:
  #         - script: npm install --prefix tour-client/tour-heroes
  #         # - script: npm run test --prefix tour-client/tour-heroes
    
  - stage: pack
    jobs:
      - job: pack_api
        steps:
          - task: Docker@2
            inputs:
              command: login
              containerRegistry: docker
          - script: |
              docker image build --file .dockers/api.dockerfile --tag tangotew/tour-api tour-api/aspnet
              docker image push tangotew/tour-api
          - task: Docker@2
            inputs:
              command: logout
              containerRegistry: docker

      - job: pack_angular
        steps:
          - task: Docker@2
            inputs:
              command: login
              containerRegistry: docker  
          - script: |
              docker image build  --file .dockers/angular.dockerfile --tag tangotew/tour-angular tour-client/tour-heroes
              docker image push tangotew/tour-angular
          - task: Docker@2
            inputs:
              command: logout
              containerRegistry: docker

           
  - stage: deploy
    jobs:
      - job: pack_api
        steps:
          - task: Docker@2
            inputs:
              command: login
              containerRegistry: docker
          - script: |
              docker image build --file aspnet/dockerfile --tag tangotew/tour-api aspnet
              docker image push tangotew/tour-api
          - task: Docker@2
            inputs:
              command: logout
              containerRegistry: docker

  # - stage: deploy
  #   jobs:
  #     - job:
  #       pool:
  #         vmImage: ubuntu-18.04
  #       steps:
  #         - task: AzureRmWebAppDeployment@4
  #           inputs:
  #             ConnectionType: "AzureRM"
  #             azureSubscription: "tangop1"
  #             appType: "webAppContainer"
  #             WebAppName: "p1proj"
  #             DockerNamespace: "tangotew"
  #             DockerRepository: "p1-project"
  