trigger:
  - master

pr:
  - master

stages:
  - stage: restore
    jobs:
      - job: restore_api
        steps:
          - script: dotnet restore tour-api/aspnet

      - job: restore_angular
        steps:
          - script: npm install --prefix tour-client/tour-heroes

  - stage: build
    jobs:
      - job: build_api
        steps:
          - script: dotnet build  tour-api/aspnet/Tour.WebApi/*csproj

      - job: build_angular
        steps:
          - script: npm run build --progress=false --prefix tour-client/tour-heroes
  
  - stage: test
    jobs: 
      - job: test_api
        steps:
          - script: dotnet test tour-api/aspnet/Tour.Testing
        
      - job: test_angular
        steps:
          - script: npm run test --prefix tour-client/tour-heroes
  
#   - stage: pack
#     jobs:
#       - job: pack_api
#         steps:
#           - task: Docker@2
#             inputs:
#               command: login
#               containerRegistry: docker
#           - script: |
#               docker image build --file aspnet/dockerfile --tag hassanibrahim27/staging-api aspnet
#               docker image push hassanibrahim27/staging-api
#           - task: Docker@2
#             inputs:
#               command: logout
#               containerRegistry: docker
              